---
title: "Lab 4"
author: "Matteo Boyer"
format: html
execute:
  echo: false
  warning: false
  keep-md: true
---

```{r}
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
```

### Question 1
```{r}
grades <- vroom(here("grades.csv"))
```


### Question 2

```{r}

stat <- grades |>
  summarise("Minimun" = min(Exam,na.rm = TRUE), "Maximum" = max(Exam, na.rm = TRUE), "Mean" = mean(Exam, na.rm = TRUE), "Median" = median(Exam, na.rm = TRUE))

knitr::kable(stat, align = "cccc", digits = 2, caption = "Exam statistics")
```

### Question 3

```{r}

na <- sum(is.na(grades$Exam))

```

`r na` students did not take the exam.

### Question 4



```{r}

ggplot(grades, aes(x=Exam)) + geom_histogram(binwidth = 1, na.rm = TRUE, fill = "white", color = "black") + labs(y = "Number of students", title = "Distribution of the exam grades")

```
### Question 5

For question 5 and 6 we keep the students that did not take the test as they are part of groups.

```{r}

nb_group <- grades |>
  group_by(Group) |>
  summarise("Number of students" = n())

knitr::kable(nb_group, align = "c", digits = 0)



```

### Question 6

```{r}

ggplot(nb_group, aes(y=`Number of students`, x = Group )) + geom_col(color = "black", fill = "white") + theme(axis.text.x = element_text(angle=90))

```

### Question 7

```{r}

exam <- grades |>
  group_by(Group) |>
  select(Exam)

ggplot(exam, aes(y=Exam, x = Group )) + geom_violin()  + theme(axis.text.x = element_text(angle=90)) + labs(y = "Exam grades", title = "Distribution of the exam grades by group")

ggplot(exam, aes(y=Exam, x = Group)) + geom_boxplot()  + theme(axis.text.x = element_text(angle=90)) + labs(y = "Exam grades", title = "Distribution of the exam grades by group")

```

### Question 8

```{r}

miss <- grades %>%
  group_by(Group) %>%
  summarize(Students_Missed_Exam = sum(is.na(Exam)))

```
### Question 9

```{r}

ggplot(miss, aes(y=`Students_Missed_Exam`, x = Group )) + geom_col(color = "black", fill = "white") + theme(axis.text.x = element_text(angle=90))+ labs(y = "Number of students who missed the exam", title = "Number of students who missed the exam by group")

```
### Question 10

```{r}

grades_long <- grades %>%
  pivot_longer(cols = -c(Id, Group), names_to = "type_exam", values_to = "Score")

```

### Question 11

```{r}
grades_NA <- grades_long %>%
  group_by(Id) %>%
  summarize(NA_total = sum(is.na(Score)))

```

### Question 12

```{r}
ggplot(grades_NA, aes(x = NA_total)) +
  geom_histogram(binwidth = 1, fill = "white", color = "black") +
  labs(
    title = "Distribution of missing grades per student",
    x = "Total Missing Grades",
    y = "Frequency"
  )

```


### Question 13

```{r}

groups <- data.frame(Group = unique(grades_long$Group))

miss_long <- grades_long %>%
  filter(type_exam == "Exam") %>%
  group_by(Group) %>%
  summarize(Students_Missed_Exam = sum(is.na(Score)))


```

### Question 14

```{r}

miss_online <- grades_long %>%
  filter(str_starts(type_exam, "Online")) %>%
  group_by(Id) %>%
  summarize(Total_Missing_Online_Test_Grades = sum(is.na(Score)))

```

### Question 15

```{r}

grades_and_nb_online_miss <- grades %>%
  left_join(miss_online, by = "Id")

ggplot(grades_and_nb_online_miss, aes(x = Exam, fill = factor(Total_Missing_Online_Test_Grades))) +
  geom_histogram(binwidth = 5, color = "black") +
  labs(title = "Distribution of exam grades Conditioned by the number of missing grades for the online
  tests",x = "Exam Grades", y = "Frequency") +
  facet_wrap(~factor(Total_Missing_Online_Test_Grades), ncol = 2) +
  scale_fill_discrete(name = "Number of missing grades for the online tests")

```
### Question 16

```{r}

any_MCQ_miss <- grades %>%
  select(Id, starts_with("MCQ")) %>%
  rowwise() %>%
  mutate(Missed = any(is.na(c_across(starts_with("MCQ"))))) %>%
  select(Id, Missed)

```

### Question 17

```{r}

any_MCQ_miss_group <- any_MCQ_miss %>%
  inner_join(grades %>% select(Id, Group), by = "Id") %>%
  group_by(Group) %>%
  summarize(P_missed = mean(Missed))

```

### Question 18

```{r}
exam_per_group <- grades %>%
  group_by(Group) %>%
  summarize(AvgGrade = mean(Exam, na.rm = TRUE))

merged_table <- inner_join(any_MCQ_miss_group, exam_per_group, by = "Group")


ggplot(merged_table, aes(x = P_missed, y = AvgGrade, label = Group)) +
  geom_point() + 
  labs(x = "Percentage of students that missed at least one MCQ per group", y = "Average exam grade per group")
```


